# Generated by Django 5.0.6 on 2024-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'Showes'), (3, 'Cloth')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdetail',
            field=models.CharField(max_length=300, verbose_name='Product Detail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=20, verbose_name='Product Name'),
        ),
    ]
